"""Final preservation check and sanitized handoff. Hashes only for sources."""
import csv
import subprocess
import sys
import zipfile
from pathlib import Path
O=Path(__file__).resolve().parent;R=O.parents[1]
sys.path.insert(0,str(O/'recovery_protocol'))
from engine import *
def put(n,v):
    p=O/n;p.parent.mkdir(parents=True,exist_ok=True)
    p.write_bytes(v.encode() if isinstance(v,str) else canonical(v)+b'\n')
e=Engine(O/'recovery_coordination');pins={k:e.state()[k] for k in PIN_KEYS}
with e.lock('/root'):
    e.recover(pins,session_mode='RESUMED_SESSION')
    e.begin('FINAL_REPORTS_AND_PRESERVATION',{'baseline':filehash(O/'PHASE4BC_S_BASELINE.json')},['outputs/preservation_check.json','outputs/final_handoff.json'])
rows=list(csv.DictReader((O/'PROTECTED_FILES_INITIAL.csv').open(encoding='utf-8-sig')));changes=[]
for i,row in enumerate(rows,1):
    p=R/row['path'];got=filehash(p) if p.is_file() else None
    if got!=row['sha256']:changes.append({'path':row['path'],'expected':row['sha256'],'observed':got})
    if i%3000==0:print('Final protected hashes',i,flush=True)
archives=[]
for a in read(O/'PHASE4BC_S_BASELINE.json')['archives']:
    p=R/a['path']
    with zipfile.ZipFile(p) as z:crc=z.testzip() is None
    archives.append({'path':a['path'],'sha256':filehash(p),'expected':a['sha256'],'crc_ok':crc,'passed':filehash(p)==a['sha256'] and crc})
reservation=read(O/'B02_B08_UNTOUCHED_CHECK.json')
source_checks=[{'holdout_id':x['holdout_id'],'hash_match':filehash(R/x['path'])==x['source_sha256'],'consumed':False,'substantive_access':False} for x in reservation['reports']]
git=subprocess.run(['git','status','--porcelain=v1','--untracked-files=all'],cwd=R,capture_output=True,check=True).stdout
(O/'GIT_STATUS_FINAL.txt').write_bytes(git)
initial=(O/'GIT_STATUS_INITIAL.txt').read_text(encoding='utf-8-sig').splitlines();final=git.decode('utf-8').splitlines()
def filtered(lines):return sorted(x for x in lines if 'analysis/phase4bc_supplement/' not in x and 'analysis/phase4bc_supplement_package.zip' not in x)
git_equal=filtered(initial)==filtered(final)
live=read(R/'analysis/reviews.json')
assert live=={},'Live review drift'
preservation={'timestamp':now(),'protected_count':len(rows),'changes':changes,'prior_archives':archives,'source_hash_checks':source_checks,'reserved':7,'untouched':7,'consumed':0,'contamination_events':0,'live_source_verified':0,'live_promoted':0,'live_controls_basis':'unchanged protected controls and empty analysis/reviews.json; no checkpoint writer invoked','git_outside_boundary_equal':git_equal,'git_drift_status':'NONE' if git_equal else 'REVIEW_REQUIRED','lane_b_executed':False,'phase4b_resumed':False,'migration':False,'skills_installed':False,'checkpoint_refreshed':False,'evidence_limit':'Recorded access and derived inventory, not OS-wide audit. Sources only streaming hashed.','passed':not changes and all(a['passed'] for a in archives) and all(a['hash_match'] for a in source_checks) and git_equal}
put('PRESERVATION_CHECK.json',preservation)
assert preservation['passed'],'Preservation gate failure; do not package as success'
tests=read(O/'RECOVERY_TEST_RESULTS.json');impl=read(O/'RECOVERY_IMPLEMENTATION_MANIFEST.json');audit=read(O/'RECOVERY_INTEGRITY_AUDIT.json');sym=read(O/'REAL_SYMLINK_TEST_RESULT.json')
put('INDEPENDENT_FINAL_REVIEW.json',{'reviewer':'/root/supplement_review','mode':'READ_ONLY_MODEL_REVIEW','engine_sha256':'39dab4c38ebda49d2f65199e3b2d6f82bf44124b05b98a9347fbe89bdced777a','test_sha256':'d9063652318ce6f46920f87607444ab3c64498c218c501b88e508693c0159b7b','targeted_corrections':'10 defects found and corrected; 7 initial control defects and3 Windows namespace/intent defects','final_targeted_review':'NO_FURTHER_BLOCKER_FOUND_WITHIN_REVIEW_SCOPE','reviewed_test_result':{'passed':46,'failed':0,'skipped':0},'not_human_approval':True,'limitations':['No independent rerun by reviewer','Synthetic continuity is not real scientific continuity','Environment symlink gate blocked','No power-loss or OS-wide source-access proof']})
attempts=[{'path':p.relative_to(O).as_posix(),'sha256':filehash(p),'tests':read(p)['tests'],'passed':read(p)['passed'],'failed':read(p)['failed']} for p in sorted((O/'test_results').glob('recovery-*.json'))]
put('RECOVERY_TEST_REPORT.md','# Recovery test report\n\nFinal **46 passed,0 failed,0 skipped**. All18 requested interruption scenarios plus crash, lock, journal, schema and independent-review regressions are exercised with invented data. Failed and intermediate attempts remain in test_results; final results are not the sum of reruns. The initial36-test attempt had one partial-state lock-reading error; fixed before finalization. Reviewer identified10 additional gaps; targeted regressions37–46 pass.\n\nOriginal Phase4BC tests223:222pass,0fail,1skip are historical and were not rerun or rewritten. Supplemental real-link test ENVIRONMENT_BLOCKED is separate. Synthetic files/database corruption fixtures are NEVER_PACKAGE; no live imports occurred. New/resumed session labels exercise protocol paths, not Codex service persistence. Separate SQLite integrity/FK test demonstrates structurally intact database with foreign-key violation fails.\n\nImmutable implementation fingerprint: '+impl['sha256']+'.\n')
put('TEST_ATTEMPT_INVENTORY.json',{'attempts':attempts,'final_result':'RECOVERY_TEST_RESULTS.json','historical_inherited_not_rerun':True})
classification='SUPPLEMENT_COMPLETE_NOT_READY_TO_RESUME'
handoff={'phase':'PHASE4BC-S','classification':classification,'phase4bc_parent':{'classification':'CONTEXT_REMEDIATION_COMPLETE_NOT_READY_TO_RESUME','context_architecture_version':'phase4bc-context-v1.0.0','context_architecture_sha256':'63927844eaac94765a7a804ab128076a88cad6eac2f534b715b08b17c4e21606','scientific_methodology_version':'phase4br-scientific-v3.0.0','scientific_methodology_sha256':'ad691060099fff81a3e75de6d4ffdfeb4a8906e006dbfbeefc80a6c601f1d07f'},'symlink_supplement':{**sym,'workspace_filesystem':'FAT32','supplemental_filesystem':'NTFS','privilege_status':'WinError1314','supplemental_test_status':sym['status']},'recovery_audit':{'interruption_events_established':None,'recovery_requests_established':3,'usage_limit_events_established':None,'usage_status_observations':2,'affected_worker_identities':3,'replay_events':'Implementation reruns observed; exact durable replay count UNKNOWN','duplicate_effects':'No duplicate authoritative effect established','partial_outputs':'Preserved failed attempts not counted as final success','unresolved_recovery_issues':['Intermediate chronology incomplete; no historical atomic chain or OS-wide access audit'],'recovery_integrity_verdict':audit['verdict'],'phase4bc_blocker_attribution':audit['blocker_attribution']},'recovery_protocol':{'version':VERSION,'sha256':impl['sha256'],'fingerprint_definition':'sorted implementation file manifest entries','canonical_state_enabled':True,'append_only_events_enabled':True,'milestone_receipts_enabled':True,'atomic_units_enabled':True,'preemption_state_enabled':True,'recovery_preflight_enabled':True,'holdout_pre_source_rule_enabled':True,'holdout_post_source_rule_enabled':True,'context_firewall_enabled':True,'canonical_state':'recovery_coordination/RECOVERY_STATE.json','bootstrap_index':'RECOVERY_COORDINATION_INDEX.json','real_source_delivery_enabled':False,'real_scientific_continuity_adapter':'UNAVAILABLE_FAIL_CLOSED'},'tests':{'inherited':{'total':223,'passed':222,'failed':0,'skipped':1,'rerun':False},'supplemental':46,'passed':46,'failed':0,'skipped':0,'real_symlink':'ENVIRONMENT_BLOCKED'},'reserved_holdout':{'selected':7,'untouched':7,'consumed':0,'contamination_events':0,'resume_start':'B02'},'live_state':{'source_verified':0,'promoted':0},'lane_b_executed':False,'phase4b_resumed':False,'phase5_started':False,'preservation':'PASS','independent_review':'READ_ONLY_MODEL_REVIEW_COMPLETED','remaining_blockers':['Real-symlink invariant not exercised because NTFS privilege blocked','Real scientific recovery requires evidence-backed clean-context continuity adapter; synthetic booleans do not authorize it'],'package':{'path':'analysis/phase4bc_supplement_package.zip','sha256':None,'receipt':'external PACKAGE_RECEIPT.json','convention':'Archived handoff references external receipt; external handoff populated only after archive hashing.'}}
put('FINAL_HANDOFF.json',handoff)
put('PHASE4B_RESUME_READINESS_SUPPLEMENT.md','# Additive readiness supplement\n\nOriginal Phase4BC: CONTEXT_REMEDIATION_COMPLETE_NOT_READY_TO_RESUME; required real-link test skipped on Drive. Supplemental result ENVIRONMENT_BLOCKED / SYMLINK_PRIVILEGE_BLOCKED on NTFS (1314). Invariant not satisfied. Retrospective: '+audit['verdict']+'; blocker '+audit['blocker_attribution']+'. Recovery toolkit46/46 passes, read-only model review completed. Real scientific continuity adapter remains unavailable and fails closed. Seven of seven reserved reports untouched, zero consumed.\n\n**'+classification+'**. No B02 access or resumption authorization. Historical results unchanged.\n')
put('EXECUTIVE_PHASE4BC_S.md','# Phase4BC-S outcome\n\n**'+classification+'**. Recovery preflight reconciled baseline and blocked symlink result without replaying completed work.14449 protected files unchanged; nine prior archives verified.\n\nG:FAT32; local C:NTFS. Real-link creation failed1314 (privilege), positive regular control passed, temporary fixture removed. Original invariant remains unproven. Historical Phase4BC223 checks unchanged (222pass/1skip). Supplemental recovery46/46 passes. Three direct recovery requests and two quota-status observations established; distinct usage windows unknown. No evidence of recovery-induced final-state corruption.\n\nSeven reports reserved, zero consumed/contaminated. Live verified/promoted zero. No Phase4B, LaneB, migration, checkpoints, skills or Phase5. Library is synthetic-tested recovery tooling, not scientific validation or production authorization. See RECOVERY_COORDINATION_INDEX.json for authoritative current state and preserved bootstrap history.\n')
put('REQUIREMENTS_TRACEABILITY.json',{'source':'Phase4BC-S user specification and recovery request','mapping':{'baseline_and_frozen_inputs':['PHASE4BC_S_BASELINE.json','RECOVERY_PREFLIGHT.json','PRESERVATION_CHECK.json'],'symlink_contract_environment_cleanup':['REAL_SYMLINK_TEST_SPEC.md','SYMLINK_ENVIRONMENT_PROBE.json','REAL_SYMLINK_TEST_RESULT.json','REAL_SYMLINK_TEST_REPORT.md'],'retrospective_ten_questions':['RECOVERY_INTEGRITY_AUDIT.json','PHASE4BC_RECOVERY_TIMELINE.jsonl'],'canonical_state_events_receipts':['recovery_protocol/engine.py','RECOVERY_COORDINATION_INDEX.json'],'schemas':['RECOVERY_STATE.schema.json','RECOVERY_EVENTS.schema.json','MILESTONE_RECEIPT.schema.json'],'18_scenarios_and_crash_regressions':['RECOVERY_TEST_RESULTS.json','recovery_protocol/test_recovery.py'],'locks_replay_quarantine':['recovery_protocol/engine.py','RECOVERY_TEST_REPORT.md'],'usage_and_context':['PREEMPTION_RECOVERY_PROTOCOL.md','RECOVERY_CONTEXT_FIREWALL.md'],'holdout_conservation':['B02_B08_UNTOUCHED_CHECK.json','PRESERVATION_CHECK.json'],'future_resume_only':['PHASE4B_RESUME_WITH_RECOVERY_PROTOCOL.md'],'independent_review':['INDEPENDENT_RETROSPECTIVE_REVIEW.json','INDEPENDENT_FINAL_REVIEW.json'],'allowlist_package':['PACKAGE_MANIFEST.json','PACKAGE_RECEIPT.json']},'explicit_limitations':['Real symlink privilege blockage','No OS-wide audit','Real scientific continuation unavailable','No power-loss guarantees']})
with e.lock('/root'):
    e.commit({'outputs/preservation_check.json':canonical(preservation),'outputs/final_handoff.json':canonical(handoff)},next_operation='PACKAGE_AND_VERIFY')
print('Final report/preservation unit committed. Protected',len(rows),'unchanged.')
