CREATE TABLE metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE sources(source_id TEXT PRIMARY KEY,sha256 TEXT UNIQUE NOT NULL CHECK(length(sha256)=64),pages INTEGER);
CREATE TABLE observations(path TEXT NOT NULL,source_id TEXT REFERENCES sources(source_id),observed_at TEXT NOT NULL,PRIMARY KEY(path,source_id));
CREATE TABLE reports(paper_report_id TEXT PRIMARY KEY,summary_name TEXT UNIQUE NOT NULL COLLATE NOCASE,source_id TEXT NOT NULL REFERENCES sources(source_id),source_path TEXT NOT NULL,legacy_status TEXT NOT NULL,scientific_state TEXT NOT NULL,manifest_json TEXT NOT NULL);
CREATE TABLE artifacts(artifact_id TEXT PRIMARY KEY,sha256 TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('RAW_REGISTERED_HISTORICAL_ARTIFACT','ACCEPTED_IMMUTABLE_ARTIFACT','REJECTED_PRESERVED_ARTIFACT')),kind TEXT NOT NULL,paper_report_id TEXT REFERENCES reports(paper_report_id),path TEXT NOT NULL,origin_path TEXT,privacy TEXT NOT NULL CHECK(privacy IN ('NEVER_PACKAGE','SYNTHETIC')),provenance_json TEXT NOT NULL);
CREATE TABLE history(history_id TEXT PRIMARY KEY,kind TEXT NOT NULL,payload_json TEXT NOT NULL);
CREATE TABLE relationships(relationship_id TEXT PRIMARY KEY,report_a TEXT REFERENCES reports(paper_report_id),report_b TEXT REFERENCES reports(paper_report_id),state TEXT NOT NULL CHECK(state IN ('CANDIDATE','CONFIRMED','REJECTED','UNRESOLVED')),evidence_json TEXT NOT NULL);
CREATE TABLE unknowns(unknown_id TEXT PRIMARY KEY,payload_json TEXT NOT NULL);
CREATE TABLE events(event_id TEXT PRIMARY KEY,event_type TEXT NOT NULL,subject TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TRIGGER events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT,'append-only events'); END;
CREATE TRIGGER events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT,'append-only events'); END;
CREATE TRIGGER artifacts_no_update BEFORE UPDATE ON artifacts BEGIN SELECT RAISE(ABORT,'immutable artifact registrations'); END;
CREATE TRIGGER artifacts_no_delete BEFORE DELETE ON artifacts BEGIN SELECT RAISE(ABORT,'retained artifact registrations'); END;
CREATE TABLE runs(run_id TEXT PRIMARY KEY,pins_json TEXT NOT NULL,phase TEXT NOT NULL DEFAULT 'SHADOW');
CREATE TABLE tasks(task_id TEXT PRIMARY KEY,run_id TEXT REFERENCES runs(run_id),paper_report_id TEXT REFERENCES reports(paper_report_id),stage TEXT NOT NULL,state TEXT NOT NULL,current_attempt TEXT,generation INTEGER NOT NULL DEFAULT 0,source_id TEXT REFERENCES sources(source_id),pins_json TEXT NOT NULL,prerequisites_json TEXT NOT NULL,max_attempts INTEGER NOT NULL DEFAULT 3);
CREATE TABLE attempts(attempt_id TEXT PRIMARY KEY,task_id TEXT REFERENCES tasks(task_id),number INTEGER NOT NULL,worker TEXT NOT NULL,token TEXT NOT NULL,generation INTEGER NOT NULL,expiry REAL NOT NULL,state TEXT NOT NULL,outbox TEXT NOT NULL,UNIQUE(task_id,number));
CREATE TABLE replay(run_id TEXT NOT NULL,task_id TEXT NOT NULL REFERENCES tasks(task_id),attempt_id TEXT NOT NULL REFERENCES attempts(attempt_id),submission_id TEXT NOT NULL,digest TEXT NOT NULL,receipt_json TEXT NOT NULL,PRIMARY KEY(run_id,task_id,attempt_id,submission_id));
CREATE TABLE accepted(task_id TEXT PRIMARY KEY REFERENCES tasks(task_id),artifact_id TEXT REFERENCES artifacts(artifact_id),valid INTEGER NOT NULL CHECK(valid IN(0,1)));
CREATE TABLE records(record_id TEXT PRIMARY KEY,kind TEXT NOT NULL,paper_report_id TEXT REFERENCES reports(paper_report_id),artifact_sha256 TEXT NOT NULL,payload_json TEXT NOT NULL,current INTEGER NOT NULL DEFAULT 1);
CREATE TABLE reviews(review_id TEXT PRIMARY KEY,artifact_sha256 TEXT NOT NULL,actor TEXT NOT NULL,decision TEXT NOT NULL,payload_json TEXT NOT NULL,current INTEGER NOT NULL CHECK(current IN(0,1)),trusted INTEGER NOT NULL CHECK(trusted IN(0,1)));
CREATE TABLE retention(sha256 TEXT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(sha256,reason));
